language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
services:
  - cassandra
before_script: |-
  cqlsh -e "CREATE KEYSPACE test WITH REPLICATION = { 'class': 'SimpleStrategy', 'replication_factor': 1 };"
notifications:
  email:
    - dmitri@toubelis.org
